#!/bin/bash



echo "Аргументы командной строки:"

echo "=========================="



count=1

for arg in "$@"; do

    echo "Аргумент $count: $arg"

    ((count++))

done



echo ""

echo "Всего аргументов: $#"

